### ISSUE TITLE
运行提示错误.

### ISSUE THREAD

**Issue by fangjunai** [pannysp/sp-printer#2]
electron-vue : 1.0.6  , win7-32, 
===================================
D:\demo\node_modules\iconv\lib\iconv.js:30 Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\demo\node_modules\iconv\build\Release\iconv.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\demo\node_modules\iconv\lib\iconv.js:27:14)
    at Object.<anonymous> (D:\demo\node_modules\iconv\lib\iconv.js:180:3)

**Comment by pannysp** [comment]
> # electron-vue : 1.0.6 , win7-32,
> D:\demo\node_modules\iconv\lib\iconv.js:30 Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
> \?\D:\demo\node_modules\iconv\build\Release\iconv.node
> at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
> at Object.Module._extensions..node (module.js:671:18)
> at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
> at Module.load (module.js:561:32)
> at tryModuleLoad (module.js:504:12)
> at Function.Module._load (module.js:496:3)
> at Module.require (module.js:586:17)
> at require (internal/module.js:11:18)
> at Object. (D:\demo\node_modules\iconv\lib\iconv.js:27:14)
> at Object. (D:\demo\node_modules\iconv\lib\iconv.js:180:3)

我已经更新readme了，你看下具体的安装操作，重新下载编译安装

**Comment by fangjunai** [comment]
电脑已安装python2.7、Visual Studio 2015、全局安装的nw-gyp；
npm install --msvs_version=2015 sp-printer  也安装成功. 
在调用的时候出错.

let printer = require('sp-printer');
new printer(function(err,msg){
    //调用this方法进行打印
    this.text('测试打印');
    this.print(function(err, msg){
        if(err){
            console.log(msg);
        }
        this.empty();
    });
});
--------------------------------------------------------
错误如下:
![_20181115103127](https://user-images.githubusercontent.com/8251679/48526172-a8048200-e8c1-11e8-9d4c-d6d4df5c9795.png)

**Comment by pannysp** [comment]
> 电脑已安装python2.7、Visual Studio 2015、全局安装的nw-gyp；
> npm install --msvs_version=2015 sp-printer 也安装成功.
> 在调用的时候出错.
> 
> ## let printer = require('sp-printer');
> new printer(function(err,msg){
> //调用this方法进行打印
> this.text('测试打印');
> this.print(function(err, msg){
> if(err){
> console.log(msg);
> }
> this.empty();
> });
> });
> 错误如下:
> ![_20181115103127](https://user-images.githubusercontent.com/8251679/48526172-a8048200-e8c1-11e8-9d4c-d6d4df5c9795.png)

你得按照Electron安装原生node模块，来安装，我这是nw安装方式，不太一样的。
